# Generated by Django 3.2.8 on 2023-04-23 22:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=10000, null=True)),
                ('varitey', models.CharField(max_length=100, null=-1)),
                ('likes', models.IntegerField(blank=True, default=0, null=True)),
                ('author', models.ManyToManyField(blank=True, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='posts', to='base.Post'),
        ),
    ]
