# Generated by Django 3.2.8 on 2023-05-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20230509_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_following',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
