# Generated by Django 3.2.8 on 2023-05-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20230517_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='direct_message_chats',
            field=models.ManyToManyField(blank=True, related_name='direct_message_chats', to='base.DirectMessageChat'),
        ),
    ]
