# Generated by Django 3.2.8 on 2023-05-19 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_user_direct_message_chats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directmessagechat',
            name='participants',
        ),
        migrations.AddField(
            model_name='directmessagechat',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directmessagechat',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
