# Generated by Django 3.2.19 on 2023-08-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20230716_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(default='default_profile.png', null=True, upload_to='images/'),
        ),
    ]
