# Generated by Django 3.2.19 on 2023-08-22 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20230820_2352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaFile',
        ),
    ]
