# Generated by Django 3.2.19 on 2023-08-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_delete_mediafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='public_id_image',
            field=models.CharField(max_length=100, null=-1),
            preserve_default=-1,
        ),
    ]
