# Generated by Django 3.2.8 on 2023-08-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_post_public_id_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_id_profile_image',
            field=models.CharField(max_length=100, null=-1),
            preserve_default=-1,
        ),
    ]
